# Generated by Django 4.0.4 on 2022-04-24 11:20

import bot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название игры')),
                ('description', models.TextField(blank=True, verbose_name='Описание игры')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(unique=True, verbose_name='Идентификатор чата')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='Ник')),
                ('info', models.TextField(blank=True, verbose_name='О себе')),
                ('game', models.ForeignKey(blank=True, on_delete=models.SET(bot.models.get_game), related_name='users', to='bot.game', verbose_name='Основная игра')),
            ],
        ),
    ]
