# Generated by Django 4.0.4 on 2022-04-24 12:03

import bot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(bot.models.get_game), related_name='users', to='bot.game', verbose_name='Основная игра'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ник'),
        ),
    ]
